name: Withings Sync

on:
  schedule:
  # Uruchomienie o 6:25
    - cron: '25 6 * * *'
    # Uruchomienie o 8:00 oraz 11:00 (minuta "0" jest wspÃ³lna)
    - cron: '0 8,11 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/bartk89/withings-sync.git

    - name: Sync Withings to Garmin
      env:
        GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME }}
        GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
        WITHINGS_ACCESS_TOKEN: ${{ secrets.WITHINGS_ACCESS_TOKEN }}
        WITHINGS_REFRESH_TOKEN: ${{ secrets.WITHINGS_REFRESH_TOKEN }}
        WITHINGS_USERID: ${{ secrets.WITHINGS_USERID }}
        WITHINGS_APP_JSON: ${{ secrets.WITHINGS_APP_JSON }}
      run: |
        echo "$WITHINGS_APP_JSON" > /tmp/withings_app.json
        WITHINGS_APP=/tmp/withings_app.json withings-sync --verbose
