name: Withings Sync

on:
  schedule:
# Uruchomienie o 6:25
    - cron: '25 6 * * *'
    # Uruchomienie o 8:00 oraz 11:00 (minuta "0" jest wsp√≥lna)
    - cron: '0 8,11 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/jaroslawhartman/withings-sync.git
    
    - name: Sync Withings to Garmin
      run: |
        withings-sync \
          -g ${{ secrets.GARMIN_USERNAME }} ${{ secrets.GARMIN_PASSWORD }} \
          --fromdate 2025-01-01
      env:
        WITHINGS_CLIENT_ID: ${{ secrets.WITHINGS_CLIENT_ID }}
        WITHINGS_CONSUMER_SECRET: ${{ secrets.WITHINGS_CLIENT_SECRET }}
        WITHINGS_AUTHORIZATION_CODE: ${{ secrets.WITHINGS_CODE }}
